# Generated by Django 4.2.7 on 2024-08-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('balance', models.BigIntegerField()),
                ('passwords', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=8)),
                ('Mobile_no', models.BigIntegerField(max_length=10)),
                ('pin', models.IntegerField(max_length=6)),
            ],
        ),
    ]
