# Generated by Django 4.2.7 on 2024-09-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
