# Generated by Django 4.2.7 on 2024-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_account_balance_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Account_no',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
