# Generated by Django 4.2.7 on 2024-10-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_account_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Account_no',
        ),
    ]
