# Generated by Django 4.2.7 on 2024-10-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_statement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='acc_no',
        ),
        migrations.AddField(
            model_name='statement',
            name='acc_no',
            field=models.ManyToManyField(related_name='account_no', to='login.account'),
        ),
    ]
