# Generated by Django 4.2.7 on 2024-10-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_statement_acc_no_statement_acc_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='statement',
        ),
    ]
