# Generated by Django 4.2.7 on 2024-10-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_delete_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID',default=1022201)),
                ('before_balance', models.BigIntegerField()),
                ('cash_flow', models.BigIntegerField()),
                ('detail', models.CharField(max_length=1000)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_no', to='login.account')),
            ],
        ),
    ]
