# Generated by Django 4.2.7 on 2024-12-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_statement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='before_balance',
            new_name='After_balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='Mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
