# Generated by Django 6.0 on 2026-01-05 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_before_balance_statement_after_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
